{% set name = "eddl-cudnn" %}  # eddl-cpu, eddl-gpu, eddl-cudnn
{% set version = "1.2" %}
{% set sha256 = "b16182c7344fa89ecbdd591885cfa625fe006b2de7a51daba568f449ca0b4a2d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cmake=3.19
    - eigen=3.3|3.4
    - protobuf==3.11.4
    - libprotobuf==3.11.4
    - zlib==1.2.11
    - openssl==1.1.1i
    - wget=1.20|1.16
    - graphviz
  run:
    - cmake=3.19
    - eigen=3.3|3.4
    - protobuf==3.11.4
    - libprotobuf==3.11.4
    - zlib==1.2.11
    - openssl==1.1.1i
    - wget=1.20|1.16
    - graphviz

test:
  commands:
    - test -d ${PREFIX}/include/eddl  # [unix]
    - test -f ${PREFIX}/include/eddl/apis/eddl.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/eddl/EDDLConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/libeddl${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'EDDL is an optimized tensor library for distributed deep learning with hardware transparency support for CPUs, GPUs and FPGAs'
  doc_url: https://deephealthproject.github.io/eddl/
  dev_url: https://github.com/deephealthproject/eddl/
