{% set name = "eddl-cpu" %}  # If this is a package for GPU, use: "eddl-gpu"
{% set version = "0.9.1b" %}
{% set sha256 = "a486d699036feb893bfd95e60405ddf8d3cd9f3e4eabb61f3e65b1b7e01a1139" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/deephealthproject/eddl/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cmake>=3.17.2
    - eigen==3.3.7
    - protobuf==3.11.4
    - libprotobuf==3.11.4  # We need to avoid problems with paths (idk why)
    - zlib==1.2.11
    - openssl==1.1.1i
    - graphviz  # Build & Run  (versions can be problematic)
    - wget
  run:
    - cmake>=3.17.2
    - eigen==3.3.7
    - protobuf==3.11.4
    - libprotobuf==3.11.4  # We need to avoid problems with paths (idk why)
    - zlib==1.2.11
    - openssl==1.1.1i
    - graphviz  # Build & Run  (versions can be problematic)
    - wget

test:
  commands:
    - test -d ${PREFIX}/include/eddl  # [unix]
    - test -f ${PREFIX}/include/eddl/apis/eddl.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/eddl/EDDLConfig.cmake  # [unix]
    - test -f ${PREFIX}/lib/libeddl${SHLIB_EXT}  # [unix]

about:
  home: https://github.com/deephealthproject/eddl
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'EDDL is an optimized tensor library for distributed deep learning with hardware transparency support for CPUs, GPUs and FPGAs'
  doc_url: https://deephealthproject.github.io/eddl/
  dev_url: https://github.com/deephealthproject/eddl/
