# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_tensor', [dirname(__file__)])
        except ImportError:
            import _tensor
            return _tensor
        if fp is not None:
            try:
                _mod = imp.load_module('_tensor', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _tensor = swig_import_helper()
    del swig_import_helper
else:
    import _tensor
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0



_tensor.DEV_CPU_swigconstant(_tensor)
DEV_CPU = _tensor.DEV_CPU

_tensor.DEV_GPU_swigconstant(_tensor)
DEV_GPU = _tensor.DEV_GPU

_tensor.DEV_FPGA_swigconstant(_tensor)
DEV_FPGA = _tensor.DEV_FPGA
class Tensor(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Tensor, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Tensor, name)
    __repr__ = _swig_repr
    __swig_setmethods__["device"] = _tensor.Tensor_device_set
    __swig_getmethods__["device"] = _tensor.Tensor_device_get
    if _newclass:
        device = _swig_property(_tensor.Tensor_device_get, _tensor.Tensor_device_set)
    __swig_setmethods__["dim"] = _tensor.Tensor_dim_set
    __swig_getmethods__["dim"] = _tensor.Tensor_dim_get
    if _newclass:
        dim = _swig_property(_tensor.Tensor_dim_get, _tensor.Tensor_dim_set)
    __swig_setmethods__["tam"] = _tensor.Tensor_tam_set
    __swig_getmethods__["tam"] = _tensor.Tensor_tam_get
    if _newclass:
        tam = _swig_property(_tensor.Tensor_tam_get, _tensor.Tensor_tam_set)
    __swig_setmethods__["size"] = _tensor.Tensor_size_set
    __swig_getmethods__["size"] = _tensor.Tensor_size_get
    if _newclass:
        size = _swig_property(_tensor.Tensor_size_get, _tensor.Tensor_size_set)
    __swig_setmethods__["ptr"] = _tensor.Tensor_ptr_set
    __swig_getmethods__["ptr"] = _tensor.Tensor_ptr_get
    if _newclass:
        ptr = _swig_property(_tensor.Tensor_ptr_get, _tensor.Tensor_ptr_set)
    __swig_setmethods__["ptr1"] = _tensor.Tensor_ptr1_set
    __swig_getmethods__["ptr1"] = _tensor.Tensor_ptr1_get
    if _newclass:
        ptr1 = _swig_property(_tensor.Tensor_ptr1_get, _tensor.Tensor_ptr1_set)
    __swig_setmethods__["ptr2"] = _tensor.Tensor_ptr2_set
    __swig_getmethods__["ptr2"] = _tensor.Tensor_ptr2_get
    if _newclass:
        ptr2 = _swig_property(_tensor.Tensor_ptr2_get, _tensor.Tensor_ptr2_set)
    __swig_setmethods__["g_ptr"] = _tensor.Tensor_g_ptr_set
    __swig_getmethods__["g_ptr"] = _tensor.Tensor_g_ptr_get
    if _newclass:
        g_ptr = _swig_property(_tensor.Tensor_g_ptr_get, _tensor.Tensor_g_ptr_set)
    __swig_destroy__ = _tensor.delete_Tensor
    __del__ = lambda self: None

    def __init__(self, *args):
        this = _tensor.new_Tensor(*args)
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_getmethods__["eqsize"] = lambda x: _tensor.Tensor_eqsize
    if _newclass:
        eqsize = staticmethod(_tensor.Tensor_eqsize)
Tensor_swigregister = _tensor.Tensor_swigregister
Tensor_swigregister(Tensor)

def Tensor_eqsize(A, B):
    return _tensor.Tensor_eqsize(A, B)
Tensor_eqsize = _tensor.Tensor_eqsize

# This file is compatible with both classic and new-style classes.


