catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

set vpp_optimize_level 0
open_project krnl_vadd
set_top krnl_vadd
add_files "/home/jorga20j/Vitis_Accel_Examples/cpp_kernels/simple_vadd/src/krnl_vadd.cpp" -cflags " -g -I /home/jorga20j/Vitis_Accel_Examples/cpp_kernels/simple_vadd/src "
open_solution solution
set_part xcu200-fsgd2104-2-e
create_clock -period 300.000000MHz -name default
config_sdx -target xocc
config_rtl -kernel_profile
config_export -vivado_optimization_level $vpp_optimize_level
config_dataflow -strict_mode warning
config_debug -enable
set_clock_uncertainty 27.000000%
config_rtl -enable_maxiConservative=1
config_interface -m_axi_addr64
config_compile -skip_transform
config_export -format ip_catalog -ipname krnl_vadd
csynth_design
close_project
puts "HLS completed successfully"
exit
